apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: python-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: devopsgoofy/api-server:1.0.4
        ports:
        - containerPort: 5000
