apiVersion: v1
kind: Service
metadata:
  name: api-client-servers-service
spec:
  type: NodePort
  selector:
    app: api-client-servers
  ports:
    - name: api-port
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
    - name: client-port
      protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30002
