apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-server
  template:
    metadata:
      labels:
        app: client-server
    spec:
      containers:
      - name: client-server
        image: your_dockerhub_username/client-server:latest
        ports:
        - containerPort: 5001
