apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: python-mongodb
spec:
  type: NodePort
  ports:
    - port: 9092
      targetPort: 9092
      nodePort: 30092
  selector:
    app: kafka