apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: python-mongodb
spec:
  type: NodePort
  ports:
    - port: 2181
      targetPort: 2181
      nodePort: 32181
  selector:
    app: zookeeper